// <auto-generated />
using System;
using AdquisicionesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdquisicionesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250320193822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("AdquisicionesAPI.Models.Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Creación"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Edición"
                        });
                });

            modelBuilder.Entity("AdquisicionesAPI.Models.Adquisicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documentacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaAdquisicion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoBienServicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Adquisiciones");
                });

            modelBuilder.Entity("AdquisicionesAPI.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Creado"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "En proceso"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Inactivo"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Finalizado"
                        });
                });

            modelBuilder.Entity("AdquisicionesAPI.Models.HistorialAdquisicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdquisicionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CampoModificado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorAnterior")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorNuevo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccionId");

                    b.ToTable("HistorialAdquisiciones");
                });

            modelBuilder.Entity("AdquisicionesAPI.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Laboratorios Bayer S.A."
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Laboratorios Distritales S.A."
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Laboratirio Medicinal S.A."
                        });
                });

            modelBuilder.Entity("AdquisicionesAPI.Models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Unidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Dirección de Medicamentos y Tecnologías en Salud"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Dirección de Enfermería"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Dirección de Medicamentos básicos"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Dirección General de Salud"
                        });
                });

            modelBuilder.Entity("AdquisicionesAPI.Models.Adquisicion", b =>
                {
                    b.HasOne("AdquisicionesAPI.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdquisicionesAPI.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdquisicionesAPI.Models.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Proveedor");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("AdquisicionesAPI.Models.HistorialAdquisicion", b =>
                {
                    b.HasOne("AdquisicionesAPI.Models.Accion", "Accion")
                        .WithMany()
                        .HasForeignKey("AccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accion");
                });
#pragma warning restore 612, 618
        }
    }
}
